In [18]:
import pandas as pd

csv_path = '/home/alberto.vicente/phd/DataDriven_UT_AlbertoVicente/19_Lucia/03_C_scan/panels_procedures_v02.csv'
panels_df = pd.read_csv(csv_path)
panels_df

,Sample name,Description,Stacking sequence,Laying up method,Curing process,Characterization methods
0,Panel 1,Cured by Hexcel (last presentation),[+/0/-/90]2s,HLU,Vacuum bag,"C-scan, XCT, DSC"
1,Panel 2,Laid up by Hexcel/ Cured at Imdea,[+/0/-/90]3s,HLU,Vacuum bag,"C-scan, XCT, DSC"
2,Panel 3,Laid up by Hexcel/ Cured at Imdea,[+/0/-/90]3s,HLU,Hot press (7bar),"C-scan (cured), XCT (uncured)"
3,Panel 4,Laid up by Hexcel/ Cured at Imdea,[+/0/-/90]3s,HLU,Vacuum bag,"C-scan, XCT"
4,Panel 5,Laid up by Hexcel/,[+/0/-/90]3s,HLU,Vacuum bag (remove film),C-scan
5,Panel 6,Laid up by Hexcel,[+/0/-/90]3s,HLU,Vacuum bag (t1),"C-scan, XCT, DSC"
6,Panel 7,Laid up by Hexcel,[+/0/-/90]3s,HLU,Vacuum bag (t2),"C-scan, XCT, DSC"
7,Panel 8,Laid up by Hexcel,[+/0/-/90]3s,HLU,Vacuum bag (t3),"C-scan, XCT, DSC"
8,Panel 9,Laid up by Hexcel,[+/0/-/90]3s,HLU,Vacuum bag (t4),"C-scan, XCT, DSC"
9,Panel 10,Laid up by Hexcel,[+/0/-/90]3s,HLU,Vacuum bag (t4),"C-scan, XCT, DSC"
10,Panel 11,Laid up by Hexcel,[+/0/-/90]3s,HLU,Vacuum bag (full vacuum maintained),C-Scan
11,Panel 12,Hexcel panel 5,[+/0/-/90]3s,AFP,Uncured,"C-scan, Tomo"
12,Panel 13,Hexcel panel 6,[+/0/-/90]3s,AFP,Vacuum bag,"C-scan, Tomo"
13,Panel 14,Hexcel panel,[+/0/-/90]3s M56+particles,AFP,Vacuum bag,"C-scan, Tomo"
14,Panel 15,Hexcel panel,[+/0/-/90]3s M56+particles,AFP,Uncured,"C-scan, Tomo"
15,Panel 16,Hexcel panel,[+/0/-/90]3s,HLU,Vacuum bag and dwell + 30min.,C-Scan
16,Panel 17,Hexcel panel,[+/0/-/90]3s,HLU,Vacuum bag and dwell + 1h30min,C-Scan
17,Panel 18,Hexcel panel,[+/0/-/90]3s M56+particles,AFP,Vacuum bag and dwell + 30min,"C-Scan, Tomo"
18,Panel 19,Hexcel panel,[+/0/-/90]3s M56+veil,AFP,Vacuum bag and dwell + 30’,"C-Scan, Tomo"
19,Panel 20,Hexcel panel,[+/0/-/90]3s M56+veil,AFP,uncured,Tomo
20,Panel 21,Hexcel panel,[+/0/-/90]3s M56+veil,AFP,Vacuum bag and dwell + 1h30min. *problem,C-scan
21,Panel 22,Imdea panel,[+/0/-/90]3s,HLU (4plies & 10min),Vacuum bag and dwell + 30min,C-scan
22,Panel 23,Imdea panel,[+/0/-/90]3s,HLU (2plies & 10min),Vacuum bag and dwell + 30min,C-scan
23,Panel 24,Imdea panel,[+/0/-/90]3s,HLU (4plies & 20min),Vacuum bag and dwell + 30min,C-scan
24,Panel 25,Imdea panel,[+/0/-/90]3s,HLU (4plies & 10min),Vacuum bag and dwell + 30min,NaN
25,Panel 26,Imdea panel,[+/0/-/90]3s,HLU (2plies & 10min),Vacuum bag and dwell + 30min,C-scan
26,Panel 27,Hexcel panel,[+/0/-/90]3s,HLU,Vacuum bag and dwell + 30min (t2),C-scan
27,Panel 28,Hexcel panel,[+/0/-/90]3s,HLU,Vacuum bag and dwell + 30min (t4),C-scan
28,Panel 29,Hexcel panel,[+/0/-/90]3s,AFP,VBO (t1) Dwell+30,C-scan
29,Panel 30,Hexcel panel,[+/0/-/90]3s,AFP,VBO (t2) Dwell+30,C-scan
30,Panel 31,Hexcel panel,[+/0/-/90]3s,AFP,VBO (t3) Dwell+30,C-scan
31,Panel 32,Hexcel panel,[+/0/-/90]3s,AFP,VBO (t4) Dwell+30,C-scan
32,Panel 33,Hexcel panel,[+/0/-/90]3s,AFP,VBO Dwell+30,C-scan
33,Panel 34,Hexcel panel,[+/0/-/90]3s M56+particles,AFP,VBO (t1) Dwell+30,C-scan
34,Panel 35,Hexcel panel,[+/0/-/90]3s M56+particles,AFP,VBO (t2) Dwell+30,C-scan
35,Panel 36,Hexcel panel,[+/0/-/90]3s M56+particles,AFP,VBO (t3) Dwell+30,C-scan
36,Panel 37,Hexcel panel,[+/0/-/90]3s M56+particles,AFP,VBO (t4) Dwell+30,C-scan
37,Panel 38,Hexcel panel,[+/0/-/90]3s,HLU modified,VBO Dwell+30,C-scan
38,Panel 39,Hexcel panel,[+/0/-/90]3s,HLU,VBO Dwell+30 sequentially,"C-Scan Initial,t1,t2,t3,t4,final"
39,Panel A1,Hexcel panel,[+/0/-/90]3s,HLU,Autoclave,NaN
40,Panel A2,Hexcel panel,[+/0/-/90]3s,AFP,Autoclave,NaN
41,Panel A3,Hexcel panel,[+/0/-/90]3s,AFP particles,Autoclave,NaN
42,Panel A4,Hexcel panel,[+/0/-/90]3s,AFP veil,Autoclave,NaN
43,Panel 40,Hexcel panel,NaN,HLU modified,uncured,NaN
44,Panel 41,Hexcel panel,[+/0/-/90]3s,AFP veil,VBO (t1) Dwell+30,C-scan
45,Panel 42,Hexcel panel,[+/0/-/90]3s,AFP veil,VBO (t2) Dwell+30,C-scan
46,Panel 43,Hexcel panel,[+/0/-/90]3s,AFP veil,VBO (t3) Dwell+30,C-scan
47,Panel 44,Hexcel panel,[+/0/-/90]s,AFP veil,VBO Dwell+30,C-scan

In [19]:
unique_combinations = panels_df[['Stacking sequence', 'Laying up method', 'Curing process']].drop_duplicates().reset_index(drop=True)
unique_combinations

,Stacking sequence,Laying up method,Curing process
0,[+/0/-/90]2s,HLU,Vacuum bag
1,[+/0/-/90]3s,HLU,Vacuum bag
2,[+/0/-/90]3s,HLU,Hot press (7bar)
3,[+/0/-/90]3s,HLU,Vacuum bag (remove film)
4,[+/0/-/90]3s,HLU,Vacuum bag (t1)
5,[+/0/-/90]3s,HLU,Vacuum bag (t2)
6,[+/0/-/90]3s,HLU,Vacuum bag (t3)
7,[+/0/-/90]3s,HLU,Vacuum bag (t4)
8,[+/0/-/90]3s,HLU,Vacuum bag (full vacuum maintained)
9,[+/0/-/90]3s,AFP,Uncured
10,[+/0/-/90]3s,AFP,Vacuum bag
11,[+/0/-/90]3s M56+particles,AFP,Vacuum bag
12,[+/0/-/90]3s M56+particles,AFP,Uncured
13,[+/0/-/90]3s,HLU,Vacuum bag and dwell + 30min.
14,[+/0/-/90]3s,HLU,Vacuum bag and dwell + 1h30min
15,[+/0/-/90]3s M56+particles,AFP,Vacuum bag and dwell + 30min
16,[+/0/-/90]3s M56+veil,AFP,Vacuum bag and dwell + 30’
17,[+/0/-/90]3s M56+veil,AFP,uncured
18,[+/0/-/90]3s M56+veil,AFP,Vacuum bag and dwell + 1h30min. *problem
19,[+/0/-/90]3s,HLU (4plies & 10min),Vacuum bag and dwell + 30min
20,[+/0/-/90]3s,HLU (2plies & 10min),Vacuum bag and dwell + 30min
21,[+/0/-/90]3s,HLU (4plies & 20min),Vacuum bag and dwell + 30min
22,[+/0/-/90]3s,HLU,Vacuum bag and dwell + 30min (t2)
23,[+/0/-/90]3s,HLU,Vacuum bag and dwell + 30min (t4)
24,[+/0/-/90]3s,AFP,VBO (t1) Dwell+30
25,[+/0/-/90]3s,AFP,VBO (t2) Dwell+30
26,[+/0/-/90]3s,AFP,VBO (t3) Dwell+30
27,[+/0/-/90]3s,AFP,VBO (t4) Dwell+30
28,[+/0/-/90]3s,AFP,VBO Dwell+30
29,[+/0/-/90]3s M56+particles,AFP,VBO (t1) Dwell+30
30,[+/0/-/90]3s M56+particles,AFP,VBO (t2) Dwell+30
31,[+/0/-/90]3s M56+particles,AFP,VBO (t3) Dwell+30
32,[+/0/-/90]3s M56+particles,AFP,VBO (t4) Dwell+30
33,[+/0/-/90]3s,HLU modified,VBO Dwell+30
34,[+/0/-/90]3s,HLU,VBO Dwell+30 sequentially
35,[+/0/-/90]3s,HLU,Autoclave
36,[+/0/-/90]3s,AFP,Autoclave
37,[+/0/-/90]3s,AFP particles,Autoclave
38,[+/0/-/90]3s,AFP veil,Autoclave
39,NaN,HLU modified,uncured
40,[+/0/-/90]3s,AFP veil,VBO (t1) Dwell+30
41,[+/0/-/90]3s,AFP veil,VBO (t2) Dwell+30
42,[+/0/-/90]3s,AFP veil,VBO (t3) Dwell+30
43,[+/0/-/90]s,AFP veil,VBO Dwell+30

In [20]:
import sys
sys.path.append('../')
import dbtools.dbtools as qrs
import dbtools.load as load
import psycopg2

try:
    conn = qrs.connect()
    print("Connected to the database")
except (Exception, psycopg2.DatabaseError) as error:
    print(error)

Connected to the database

In [21]:
existing_fabrications = qrs.get_data('fabrications')
existing_names = set(existing_fabrications['name_fabrication'])

fabrication_ids = []

for idx, row in unique_combinations.iterrows():
    laying_up = row['Laying up method']
    curing = row['Curing process']
    stacking = row['Stacking sequence']

    name = f"AROA_{idx + 1:02d}_{laying_up}_{curing}".replace(' ', '_')

    if name in existing_names:
        fabrication_id = int(existing_fabrications.loc[existing_fabrications['name_fabrication'] == name, 'id_fabrication'].iloc[0])
        print(f"Fabrication '{name}' already exists with ID: {fabrication_id}")
    else:
        additional_metadata = [
            {'key': 'laying_up_method', 'value': laying_up, 'type': 'nominal'},
            {'key': 'curing_process', 'value': curing, 'type': 'text'},
        ]
        if pd.notna(stacking):
            additional_metadata.append({'key': 'stacking_sequence', 'value': stacking, 'type': 'nominal'})

        fabrication_id = load.load_fabrication(conn, name, additional_metadata)
        existing_names.add(name)

    fabrication_ids.append(fabrication_id)

unique_combinations['fabrication_id'] = fabrication_ids
unique_combinations

Fabrication 'AROA_01_HLU_Vacuum_bag' already exists with ID: 15
Fabrication 'AROA_02_HLU_Vacuum_bag' already exists with ID: 16
Fabrication 'AROA_03_HLU_Hot_press__(7bar)' already exists with ID: 17
Fabrication 'AROA_04_HLU_Vacuum_bag_(remove_film)' already exists with ID: 18
Fabrication 'AROA_05_HLU_Vacuum_bag_(t1)' already exists with ID: 19
Fabrication 'AROA_06_HLU_Vacuum_bag_(t2)' already exists with ID: 20
Fabrication 'AROA_07_HLU_Vacuum_bag_(t3)' already exists with ID: 21
Fabrication 'AROA_08_HLU_Vacuum_bag_(t4)' already exists with ID: 22
Fabrication 'AROA_09_HLU_Vacuum_bag_(full_vacuum_maintained)' already exists with ID: 23
Fabrication 'AROA_10_AFP_Uncured' already exists with ID: 24
Fabrication 'AROA_11_AFP_Vacuum_bag' already exists with ID: 25
Fabrication 'AROA_12_AFP_Vacuum_bag' already exists with ID: 26
Fabrication 'AROA_13_AFP_Uncured' already exists with ID: 27
Fabrication 'AROA_14_HLU_Vacuum_bag_and_dwell_+_30min.' already exists with ID: 28
Fabrication 'AROA_15_HLU_Vacuum_bag_and_dwell_+_1h30min' already exists with ID: 29
Fabrication 'AROA_16_AFP_Vacuum_bag_and_dwell_+_30min' already exists with ID: 30
Fabrication 'AROA_17_AFP_Vacuum_bag_and_dwell_+_30’' already exists with ID: 31
Fabrication 'AROA_18_AFP_uncured' already exists with ID: 32
Fabrication 'AROA_19_AFP_Vacuum_bag_and_dwell_+_1h30min._*problem' already exists with ID: 33
Fabrication 'AROA_20_HLU_(4plies_&_10min)_Vacuum_bag_and_dwell_+_30min' already exists with ID: 34
Fabrication 'AROA_21_HLU_(2plies_&_10min)_Vacuum_bag_and_dwell_+_30min' already exists with ID: 35
Fabrication 'AROA_22_HLU_(4plies_&_20min)_Vacuum_bag_and_dwell_+_30min' already exists with ID: 36
Fabrication 'AROA_23_HLU_Vacuum_bag_and_dwell_+_30min_(t2)' already exists with ID: 37
Fabrication 'AROA_24_HLU_Vacuum_bag_and_dwell_+_30min_(t4)' already exists with ID: 38
Fabrication 'AROA_25_AFP_VBO_(t1)_Dwell+30' already exists with ID: 39
Fabrication 'AROA_26_AFP_VBO_(t2)_Dwell+30' already exists with ID: 40
Fabrication 'AROA_27_AFP_VBO_(t3)_Dwell+30' already exists with ID: 41
Fabrication 'AROA_28_AFP_VBO_(t4)_Dwell+30' already exists with ID: 42
Fabrication 'AROA_29_AFP_VBO_Dwell+30' already exists with ID: 43
Fabrication 'AROA_30_AFP_VBO_(t1)_Dwell+30' already exists with ID: 44
Fabrication 'AROA_31_AFP_VBO_(t2)_Dwell+30' already exists with ID: 45
Fabrication 'AROA_32_AFP_VBO_(t3)_Dwell+30' already exists with ID: 46
Fabrication 'AROA_33_AFP_VBO_(t4)_Dwell+30' already exists with ID: 47
Fabrication 'AROA_34_HLU_modified_VBO_Dwell+30' already exists with ID: 48
Fabrication 'AROA_35_HLU_VBO_Dwell+30_sequentially' already exists with ID: 49
Fabrication 'AROA_36_HLU_Autoclave' already exists with ID: 50
Fabrication 'AROA_37_AFP_Autoclave' already exists with ID: 51
Fabrication 'AROA_38_AFP_particles_Autoclave' already exists with ID: 52
Fabrication 'AROA_39_AFP_veil_Autoclave' already exists with ID: 53
Fabrication 'AROA_40_HLU_modified_uncured' already exists with ID: 54
Fabrication 'AROA_41_AFP_veil_VBO_(t1)_Dwell+30' already exists with ID: 55
Fabrication 'AROA_42_AFP_veil_VBO_(t2)_Dwell+30' already exists with ID: 56
Fabrication 'AROA_43_AFP_veil_VBO_(t3)_Dwell+30' already exists with ID: 57
Fabrication 'AROA_44_AFP_veil_VBO_Dwell+30' already exists with ID: 58

,Stacking sequence,Laying up method,Curing process,fabrication_id
0,[+/0/-/90]2s,HLU,Vacuum bag,15
1,[+/0/-/90]3s,HLU,Vacuum bag,16
2,[+/0/-/90]3s,HLU,Hot press (7bar),17
3,[+/0/-/90]3s,HLU,Vacuum bag (remove film),18
4,[+/0/-/90]3s,HLU,Vacuum bag (t1),19
5,[+/0/-/90]3s,HLU,Vacuum bag (t2),20
6,[+/0/-/90]3s,HLU,Vacuum bag (t3),21
7,[+/0/-/90]3s,HLU,Vacuum bag (t4),22
8,[+/0/-/90]3s,HLU,Vacuum bag (full vacuum maintained),23
9,[+/0/-/90]3s,AFP,Uncured,24
10,[+/0/-/90]3s,AFP,Vacuum bag,25
11,[+/0/-/90]3s M56+particles,AFP,Vacuum bag,26
12,[+/0/-/90]3s M56+particles,AFP,Uncured,27
13,[+/0/-/90]3s,HLU,Vacuum bag and dwell + 30min.,28
14,[+/0/-/90]3s,HLU,Vacuum bag and dwell + 1h30min,29
15,[+/0/-/90]3s M56+particles,AFP,Vacuum bag and dwell + 30min,30
16,[+/0/-/90]3s M56+veil,AFP,Vacuum bag and dwell + 30’,31
17,[+/0/-/90]3s M56+veil,AFP,uncured,32
18,[+/0/-/90]3s M56+veil,AFP,Vacuum bag and dwell + 1h30min. *problem,33
19,[+/0/-/90]3s,HLU (4plies & 10min),Vacuum bag and dwell + 30min,34
20,[+/0/-/90]3s,HLU (2plies & 10min),Vacuum bag and dwell + 30min,35
21,[+/0/-/90]3s,HLU (4plies & 20min),Vacuum bag and dwell + 30min,36
22,[+/0/-/90]3s,HLU,Vacuum bag and dwell + 30min (t2),37
23,[+/0/-/90]3s,HLU,Vacuum bag and dwell + 30min (t4),38
24,[+/0/-/90]3s,AFP,VBO (t1) Dwell+30,39
25,[+/0/-/90]3s,AFP,VBO (t2) Dwell+30,40
26,[+/0/-/90]3s,AFP,VBO (t3) Dwell+30,41
27,[+/0/-/90]3s,AFP,VBO (t4) Dwell+30,42
28,[+/0/-/90]3s,AFP,VBO Dwell+30,43
29,[+/0/-/90]3s M56+particles,AFP,VBO (t1) Dwell+30,44
30,[+/0/-/90]3s M56+particles,AFP,VBO (t2) Dwell+30,45
31,[+/0/-/90]3s M56+particles,AFP,VBO (t3) Dwell+30,46
32,[+/0/-/90]3s M56+particles,AFP,VBO (t4) Dwell+30,47
33,[+/0/-/90]3s,HLU modified,VBO Dwell+30,48
34,[+/0/-/90]3s,HLU,VBO Dwell+30 sequentially,49
35,[+/0/-/90]3s,HLU,Autoclave,50
36,[+/0/-/90]3s,AFP,Autoclave,51
37,[+/0/-/90]3s,AFP particles,Autoclave,52
38,[+/0/-/90]3s,AFP veil,Autoclave,53
39,NaN,HLU modified,uncured,54
40,[+/0/-/90]3s,AFP veil,VBO (t1) Dwell+30,55
41,[+/0/-/90]3s,AFP veil,VBO (t2) Dwell+30,56
42,[+/0/-/90]3s,AFP veil,VBO (t3) Dwell+30,57
43,[+/0/-/90]s,AFP veil,VBO Dwell+30,58

In [22]:
materials = qrs.get_data('materials')
materials

   id_material              name_material
0           15       Fibra IM7 Resina M56
1           16  Material Hexcel 0.508 CPT
2           20       Placeholder Material

In [23]:
# Set the material_id to use when loading the panels below
material_id = 15

In [24]:
existing_panels = qrs.get_data('panels')
existing_panel_names = set(existing_panels['name_panel'])

def combo_key(row):
    return (
        row['Stacking sequence'] if pd.notna(row['Stacking sequence']) else None,
        row['Laying up method'],
        row['Curing process'],
    )

fabrication_lookup = {combo_key(row): row['fabrication_id'] for _, row in unique_combinations.iterrows()}

# Placeholder dimensions until real measurements are available
height = width = thickness = 1.0

panel_ids = []

for _, row in panels_df.iterrows():
    name = row['Sample name']

    if name in existing_panel_names:
        panel_id = int(existing_panels.loc[existing_panels['name_panel'] == name, 'id_panel'].iloc[0])
        print(f"Panel '{name}' already exists with ID: {panel_id}")
        panel_ids.append(panel_id)
        continue

    fabrication_id = int(fabrication_lookup[combo_key(row)])
    description = row['Description'] if pd.notna(row['Description']) else None

    additional_metadata = []
    if pd.notna(row['Stacking sequence']):
        additional_metadata.append({'key': 'stacking_sequence', 'value': row['Stacking sequence'], 'type': 'nominal'})
    if pd.notna(row['Characterization methods']):
        additional_metadata.append({'key': 'characterization_methods', 'value': row['Characterization methods'], 'type': 'text'})

    panel_id = load.load_panel(
        conn, name, material_id, fabrication_id, height, width, thickness,
        description=description, additional_metadata=additional_metadata
    )
    existing_panel_names.add(name)
    panel_ids.append(panel_id)

panels_df['panel_id'] = panel_ids
panels_df

Panel 'Panel 1' loaded with ID: 16
Panel 'Panel 2' loaded with ID: 17
Panel 'Panel 3' loaded with ID: 18
Panel 'Panel 4' loaded with ID: 19
Panel 'Panel 5' loaded with ID: 20
Panel 'Panel 6' loaded with ID: 21
Panel 'Panel 7' loaded with ID: 22
Panel 'Panel 8' loaded with ID: 23
Panel 'Panel 9' loaded with ID: 24
Panel 'Panel 10' loaded with ID: 25
Panel 'Panel 11' loaded with ID: 26
Panel 'Panel 12' loaded with ID: 27
Panel 'Panel 13' loaded with ID: 28
Panel 'Panel 14' loaded with ID: 29
Panel 'Panel 15' loaded with ID: 30
Panel 'Panel 16' loaded with ID: 31
Panel 'Panel 17' loaded with ID: 32
Panel 'Panel 18' loaded with ID: 33
Panel 'Panel 19' loaded with ID: 34
Panel 'Panel 20' loaded with ID: 35
Panel 'Panel 21' loaded with ID: 36
Panel 'Panel 22' loaded with ID: 37
Panel 'Panel 23' loaded with ID: 38
Panel 'Panel 24' loaded with ID: 39
Panel 'Panel 25' loaded with ID: 40
Panel 'Panel 26' loaded with ID: 41
Panel 'Panel 27' loaded with ID: 42
Panel 'Panel 28' loaded with ID: 43
Panel 'Panel 29' loaded with ID: 44
Panel 'Panel 30' loaded with ID: 45
Panel 'Panel 31' loaded with ID: 46
Panel 'Panel 32' loaded with ID: 47
Panel 'Panel 33' loaded with ID: 48
Panel 'Panel 34' loaded with ID: 49
Panel 'Panel 35' loaded with ID: 50
Panel 'Panel 36' loaded with ID: 51
Panel 'Panel 37' loaded with ID: 52
Panel 'Panel 38' loaded with ID: 53
Panel 'Panel 39' loaded with ID: 54
Panel 'Panel A1' loaded with ID: 55
Panel 'Panel A2' loaded with ID: 56
Panel 'Panel A3' loaded with ID: 57
Panel 'Panel A4' loaded with ID: 58
Panel 'Panel 40' loaded with ID: 59
Panel 'Panel 41' loaded with ID: 60
Panel 'Panel 42' loaded with ID: 61
Panel 'Panel 43' loaded with ID: 62
Panel 'Panel 44' loaded with ID: 63

,Sample name,Description,Stacking sequence,Laying up method,Curing process,Characterization methods,panel_id
0,Panel 1,Cured by Hexcel (last presentation),[+/0/-/90]2s,HLU,Vacuum bag,"C-scan, XCT, DSC",16
1,Panel 2,Laid up by Hexcel/ Cured at Imdea,[+/0/-/90]3s,HLU,Vacuum bag,"C-scan, XCT, DSC",17
2,Panel 3,Laid up by Hexcel/ Cured at Imdea,[+/0/-/90]3s,HLU,Hot press (7bar),"C-scan (cured), XCT (uncured)",18
3,Panel 4,Laid up by Hexcel/ Cured at Imdea,[+/0/-/90]3s,HLU,Vacuum bag,"C-scan, XCT",19
4,Panel 5,Laid up by Hexcel/,[+/0/-/90]3s,HLU,Vacuum bag (remove film),C-scan,20
5,Panel 6,Laid up by Hexcel,[+/0/-/90]3s,HLU,Vacuum bag (t1),"C-scan, XCT, DSC",21
6,Panel 7,Laid up by Hexcel,[+/0/-/90]3s,HLU,Vacuum bag (t2),"C-scan, XCT, DSC",22
7,Panel 8,Laid up by Hexcel,[+/0/-/90]3s,HLU,Vacuum bag (t3),"C-scan, XCT, DSC",23
8,Panel 9,Laid up by Hexcel,[+/0/-/90]3s,HLU,Vacuum bag (t4),"C-scan, XCT, DSC",24
9,Panel 10,Laid up by Hexcel,[+/0/-/90]3s,HLU,Vacuum bag (t4),"C-scan, XCT, DSC",25
10,Panel 11,Laid up by Hexcel,[+/0/-/90]3s,HLU,Vacuum bag (full vacuum maintained),C-Scan,26
11,Panel 12,Hexcel panel 5,[+/0/-/90]3s,AFP,Uncured,"C-scan, Tomo",27
12,Panel 13,Hexcel panel 6,[+/0/-/90]3s,AFP,Vacuum bag,"C-scan, Tomo",28
13,Panel 14,Hexcel panel,[+/0/-/90]3s M56+particles,AFP,Vacuum bag,"C-scan, Tomo",29
14,Panel 15,Hexcel panel,[+/0/-/90]3s M56+particles,AFP,Uncured,"C-scan, Tomo",30
15,Panel 16,Hexcel panel,[+/0/-/90]3s,HLU,Vacuum bag and dwell + 30min.,C-Scan,31
16,Panel 17,Hexcel panel,[+/0/-/90]3s,HLU,Vacuum bag and dwell + 1h30min,C-Scan,32
17,Panel 18,Hexcel panel,[+/0/-/90]3s M56+particles,AFP,Vacuum bag and dwell + 30min,"C-Scan, Tomo",33
18,Panel 19,Hexcel panel,[+/0/-/90]3s M56+veil,AFP,Vacuum bag and dwell + 30’,"C-Scan, Tomo",34
19,Panel 20,Hexcel panel,[+/0/-/90]3s M56+veil,AFP,uncured,Tomo,35
20,Panel 21,Hexcel panel,[+/0/-/90]3s M56+veil,AFP,Vacuum bag and dwell + 1h30min. *problem,C-scan,36
21,Panel 22,Imdea panel,[+/0/-/90]3s,HLU (4plies & 10min),Vacuum bag and dwell + 30min,C-scan,37
22,Panel 23,Imdea panel,[+/0/-/90]3s,HLU (2plies & 10min),Vacuum bag and dwell + 30min,C-scan,38
23,Panel 24,Imdea panel,[+/0/-/90]3s,HLU (4plies & 20min),Vacuum bag and dwell + 30min,C-scan,39
24,Panel 25,Imdea panel,[+/0/-/90]3s,HLU (4plies & 10min),Vacuum bag and dwell + 30min,NaN,40
25,Panel 26,Imdea panel,[+/0/-/90]3s,HLU (2plies & 10min),Vacuum bag and dwell + 30min,C-scan,41
26,Panel 27,Hexcel panel,[+/0/-/90]3s,HLU,Vacuum bag and dwell + 30min (t2),C-scan,42
27,Panel 28,Hexcel panel,[+/0/-/90]3s,HLU,Vacuum bag and dwell + 30min (t4),C-scan,43
28,Panel 29,Hexcel panel,[+/0/-/90]3s,AFP,VBO (t1) Dwell+30,C-scan,44
29,Panel 30,Hexcel panel,[+/0/-/90]3s,AFP,VBO (t2) Dwell+30,C-scan,45
30,Panel 31,Hexcel panel,[+/0/-/90]3s,AFP,VBO (t3) Dwell+30,C-scan,46
31,Panel 32,Hexcel panel,[+/0/-/90]3s,AFP,VBO (t4) Dwell+30,C-scan,47
32,Panel 33,Hexcel panel,[+/0/-/90]3s,AFP,VBO Dwell+30,C-scan,48
33,Panel 34,Hexcel panel,[+/0/-/90]3s M56+particles,AFP,VBO (t1) Dwell+30,C-scan,49
34,Panel 35,Hexcel panel,[+/0/-/90]3s M56+particles,AFP,VBO (t2) Dwell+30,C-scan,50
35,Panel 36,Hexcel panel,[+/0/-/90]3s M56+particles,AFP,VBO (t3) Dwell+30,C-scan,51
36,Panel 37,Hexcel panel,[+/0/-/90]3s M56+particles,AFP,VBO (t4) Dwell+30,C-scan,52
37,Panel 38,Hexcel panel,[+/0/-/90]3s,HLU modified,VBO Dwell+30,C-scan,53
38,Panel 39,Hexcel panel,[+/0/-/90]3s,HLU,VBO Dwell+30 sequentially,"C-Scan Initial,t1,t2,t3,t4,final",54
39,Panel A1,Hexcel panel,[+/0/-/90]3s,HLU,Autoclave,NaN,55
40,Panel A2,Hexcel panel,[+/0/-/90]3s,AFP,Autoclave,NaN,56
41,Panel A3,Hexcel panel,[+/0/-/90]3s,AFP particles,Autoclave,NaN,57
42,Panel A4,Hexcel panel,[+/0/-/90]3s,AFP veil,Autoclave,NaN,58
43,Panel 40,Hexcel panel,NaN,HLU modified,uncured,NaN,59
44,Panel 41,Hexcel panel,[+/0/-/90]3s,AFP veil,VBO (t1) Dwell+30,C-scan,60
45,Panel 42,Hexcel panel,[+/0/-/90]3s,AFP veil,VBO (t2) Dwell+30,C-scan,61
46,Panel 43,Hexcel panel,[+/0/-/90]3s,AFP veil,VBO (t3) Dwell+30,C-scan,62
47,Panel 44,Hexcel panel,[+/0/-/90]s,AFP veil,VBO Dwell+30,C-scan,63